---
- hosts: 172.31.10.217
  become: yes
  tasks: 
  - name: i want to install direct linex command
    command: hostname -f
    register: myfristtaskresult



  - name: i want to frist task result 
    debug:
       msg: "{{myfristtaskresult}}"   
