---
- hosts: [mywebsers]

  become: yes 
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubuntu node
    apt:
      name: "{{myserverpactonubuntu}}"
      state: present 
    when: ansible_os_family =="Debian"
  
  - name: i want to start webserver on ubuntu node
    service:
       name: "{{myserverpactonubuntu}}"
       state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat node
    ansible.builtin.dnf:
      name: "{{myserverpactonRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i wnat to start webserver on RedHat node
    service:
        name: "{{myserverpactonRedHat}}"
        state: started
    when: ansible_os_family =="RedHat"



      




  # "RedHat" =="Debian"