---
- name: copy tomuser file into node side 
  template: 
    src: templetes/mytomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy context file into node side
  template: 
    src: templetes/mytomcontext.j2 
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml


- name: host context into node side 
  template: 
    src: templetes/hostcontext.j2 
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml